# Generated by Django 6.0.1 on 2026-01-15 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.PositiveSmallIntegerField(help_text="cm")),
                ("weight", models.FloatField(help_text="kg")),
                ("waist", models.PositiveSmallIntegerField(help_text="cm")),
                ("disease", models.CharField(blank=True, max_length=120)),
                (
                    "goal",
                    models.CharField(
                        choices=[("M", "Maintain"), ("C", "Cut"), ("B", "Bulk")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
